export const PlanetData = {
  Sun: {
    name: "Sun",
    description: "The Sun is the star at the center of our solar system and contains almost all of its mass.",
    fact: "While the Sun appears yellow to us on Earth, it actually looks white from space!",
    details:
      "The Sun is a massive 4.6 billion year old star, powered by intense nuclear fusion in its core, generating extreme amounts of energy for all life on Earth to flourish.",
    type: "Star",
    diameter: "1,391,400 km",
    distance: "0 km",
    dayLength: "About 27 Earth days",
    yearLength: "225-250 million years",
    moons: ["Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune",],
    image: "images/display/sunDisplay.png",
    caption: "The Sun captured in extreme ultraviolet light.",
    credit: "ESA & NASA/Solar Orbiter/EUI team",
    extraStatLabel: "Temperature of the Sun's Core",
    extraStat: "~15 million °C",
  },

  Mercury: {
    name: "Mercury",
    description: "It's the closest planet to the Sun with extreme variance in temperatures.",
    fact: "Isn't it cool that a day on Mercury is longer than its year?",
    details:
      "Mercury is the smallest planet in the solar system and has a heavily cratered rocky surface. Temperatures swing dramatically between day and night due to its lack of atmosphere.",
    type: "Terrestrial Planet",
    diameter: "4,879 km",
    distance: "57.9 million km",
    dayLength: "59 Earth days",
    yearLength: "88 Earth days",
    moons: "0",
    numMoons: "0",
    image: "images/display/mercuryDisplay.jpg",
    caption: "Mercury on the Messenger aircraft's first flyby of the planet.",
    credit: "NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington",
    extraStatLabel: "Temperature Range",
    extraStat: "-180°C to 430°C",
  },

  Venus: {
    name: "Venus",
    description: "Venus, the second planet, is a rocky one, but is wrapped in thick clouds and the hottest planet in the entire solar system.",
    fact: "Venus spins extremely slowly and backwards compared to most planets.",
    details:
      "Venus is similar in size to Earth but has a dense carbon dioxide atmosphere that entraps heat through an extreme greenhouse effect. Its surface is hot enough to melt lead.",
    type: "Terrestrial Planet",
    diameter: "12,104 km",
    distance: "108.2 million km",
    dayLength: "243 Earth days",
    yearLength: "225 Earth days",
    moons: "0",
    numMoons: "0",
    image: "images/display/venusDisplay.jpg",
    caption: "Venus taken by NASA's Mariner 10 Spacecraft.",
    credit: "NASA",
    extraStatLabel: "Hottest Surface Temperature",
    extraStat: "~465°C",   
  },

  Earth: {
    name: "Earth",
    description: "Earth is the only known planet with liquid water on its surface and life.",
    fact: "Did you know that 71% of Earth's surface is covered by water?",
    details:
      "Earth is the third planet from the Sun and has a protective atmosphere, active geology, and a strong magnetic field. It is the only known planet in the universe to harbor and support life.",
    type: "Terrestrial Planet",
    diameter: "12,742 km",
    distance: "149.6 million km",
    dayLength: "24 hours",
    yearLength: "365.25 days",
    moons: ["Moon"],
    numMoons: "1",
    image: "images/display/earthDisplay.jpg",
    caption: "Earth. Our home.",
    credit: "ESO/M. Kornmesser",
    extraStatLabel: "Surface Water Coverage",
    extraStat: "About 71% covered by water",
  },

  Mars: {
    name: "Mars",
    description: "Mars is a desert world known as the Red Planet because of its rusty surface comprised of iron.",
    fact: "Mars has the tallest volcano in the solar system: Olympus Mons.",
    details:
      "Mars has seasons, polar ice caps, canyons, and evidence that liquid water once flowed on its surface. It provides some of the most hopeful indications of extra-terrestrial life.",
    type: "Terrestrial Planet",
    diameter: "6,779 km",
    distance: "227.9 million km",
    dayLength: "24.6 hours",
    yearLength: "687 Earth days",
    moons: ["Phobos", "Deimos"],
    numMoons: "2",
    image: "images/display/marsDisplay.jpg",
    caption: "An image of Mars centered on the Valles Marineris canyon system.",
    credit: "JPL-Caltech/NASA",
    extraStatLabel: "Height of Olympus Mons",
    extraStat: "~22 km",
  },

  AsteroidBelt: {
    name: "The Asteroid Belt",
    description: "The Asteroid Belt is a region between Mars and Jupiter filled with rocky and metallic objects.",
    fact: "The belt is actually so sparsely filled that its combined total mass is only ~4% of our moons!",
    details:
      "The Asteroid Belt lies between the orbits of Mars and Jupiter. It contains dwarf planet Ceres and millions of other smaller bodies that are vestiges of the early formation of the solar system.",
    type: "Asteroid Region",
    diameter: "About 140 million km wide",
    distance: "Between 329 and 478 million km",
    dayLength: "Varies by object",
    yearLength: "About 3 to 6 Earth years",
    moons: ["Ceres", "Vesta", "Pallas", "Hygiea"],
    image: "images/display/asteroidbelt.png",
    caption: "An artist's concept of Arrokoth, an asteroid found in the Kuiper Belt.",
    credit: "Science Photo Library/Alamy By Jonathan O'Callaghan",
    numMoons: ">1 Million",
    extraStatLabel: "Average Distance between Asteroids",
    extraStat: "965,000 km",
  },

  Jupiter: {
    name: "Jupiter",
    description: "Jupiter is the largest planet in the solar system, a gas giant with powerful storms.",
    fact: "Did you know that the Great Red Spot, Jupiter's largest storm, is bigger than Earth itself?",
    details:
      "Jupiter is made mostly of hydrogen and helium. It stands out for its enormous size, strong magnetic field, and countless moons.",
    type: "Gas Giant",
    diameter: "139,820 km",
    distance: "778.5 million km",
    dayLength: "9.9 hours",
    yearLength: "11.86 Earth years",
    moons: ["Io", "Europa", "Ganymede", "Callisto"],
    numMoons: "95",
    image: "images/display/jupiterDisplay.jpg",
    caption: "Jupiter simulated in its true colors by NASA's Cassini Spacecraft.",
    credit: "NASA/JPL/University of Arizona",
    extraStatLabel: "Total Mass",
    extraStat: "More than twice all the other planets combined!",
  },

  Saturn: {
    name: "Saturn",
    description: "Saturn is famous for its bright and complex ring system.",
    fact: "Saturn is so low in density that it would float in water!",
    details:
      "Saturn is a gas giant composed mainly of hydrogen and helium. Its renowned rings are made mostly of ice particles and rocky debris, and it has many interesting moons.",
    type: "Gas Giant",
    diameter: "116,460 km",
    distance: "1.43 billion km",
    dayLength: "10.7 hours",
    yearLength: "29.45 Earth years",
    moons: ["Titan", "Enceladus", "Rhea", "Iapetus"],
    numMoons: "146+",
    image: "images/display/saturnDisplay.jpg",
    caption: "Saturn as seen by the Hubble Space Telescope.",
    credit: "NASA, ESA, A. Simon (Goddard Space Flight Center), and M.H. Wong (University of California, Berkeley)",
    extraStatLabel: "Ring Span",
    extraStat: "~273,000 km",
  },

  Uranus: {
    name: "Uranus",
    description: "Uranus is the seventh planet from the sun, an large ice gas giant.",
    fact: "Uranus is actually also surrounded by rings, 13 of them! See the picture.",
    details:
      "Uranus is an ice cold planet whose atmosphere contains methane and ammonia. Its extreme tilt leads to extreme seasons, different to any other planet.",
    type: "Ice Giant",
    diameter: "50,724 km",
    distance: "2.87 billion km",
    dayLength: "17.2 hours",
    yearLength: "84 Earth years",
    moons: ["Titania", "Oberon", "Umbriel", "Ariel", "Miranda"],
    numMoons: "28",
    image: "images/display/uranusDisplay.jpg",
    caption: "Uranus taken with its rings.",
    credit: "ESA/Hubble & NASA, L. Lamy / Observatoire de Paris",
    extraStatLabel: "Axial Tilt",
    extraStat: "About 98°",
  },

  Neptune: {
    name: "Neptune",
    description: "Neptune, an ice gas giant, is the most distant planet from the sun.",
    fact: "Did you know that Neptune has the fastest winds in the solar system?",
    details:
      "Neptune is the last planet from the Sun and has a violent atmosphere with storms and supersonic winds. Its blue appearance comes from methane in the atmosphere.",
    type: "Ice Giant",
    diameter: "49,244 km",
    distance: "4.5 billion km",
    dayLength: "16.1 hours",
    yearLength: "164.8 Earth years",
    moons: ["Triton", "Proteus", "Nereid"],
    numMoons: "16",
    image: "images/display/neptuneDisplay.jpg",
    caption: "Neptune with its rings, a rare sight on camera.",
    credit: "Unknown",
    extraStatLabel: "Fastest Winds",
    extraStat: "Over 2,000 km/h",
  },
};